Vagrant.configure(2) do |config|
  config.vm.box = "MSEdge.Win10_RS1"
  config.vm.box_url = "boxes/MSEdge.Win10_RS1.Vagrant.box"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
end
